"""add created_at to sessions

Revision ID: 080b852c4f2f
Revises: f22c2b63da09
Create Date: 2026-03-03 19:47:23.602133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '080b852c4f2f'
down_revision: Union[str, Sequence[str], None] = 'f22c2b63da09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'created_at')
    # ### end Alembic commands ###
