"""add indexes to improve query performance

Revision ID: 54550ae9b5b2
Revises: 47ff52898c7e
Create Date: 2026-03-06 14:28:41.459360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54550ae9b5b2'
down_revision: Union[str, Sequence[str], None] = '47ff52898c7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sessions_owner_id'), 'sessions', ['owner_id'], unique=False)
    op.create_index(op.f('ix_sessions_skill_id'), 'sessions', ['skill_id'], unique=False)
    op.create_index(op.f('ix_sessions_topics_id'), 'sessions', ['topics_id'], unique=False)
    op.create_index(op.f('ix_skills_owner_id'), 'skills', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skills_owner_id'), table_name='skills')
    op.drop_index(op.f('ix_sessions_topics_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_skill_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_owner_id'), table_name='sessions')
    # ### end Alembic commands ###
